# This will run on Travis' 'new' container-based infrastructure
sudo: false
language: cpp
# Blacklist
branches:
  only:
  - gh-pages

# Environment variables
env:
  global:
    - GH_REPO_WEB: web
    - GH_REPO_OCRA_RECIPES: ocra-recipes/ocra-recipes
    - GH_REPO_OCRA_WBI: ocra-recipes/ocra-wbi-plugins
    - DOXYFILE_OCRA_RECIPES: $TRAVIS_BUILD_DIR/code_docs/ocra-recipes/docs/Doxyfile_Travis
    - DOXYFILE_OCRA_WBI: $TRAVIS_BUILD_DIR/code_docs/ocra-wbi-plugins/docs/Doxyfile_Travis
    - GH_REPO_REF: github.com/ocra-recipes/web.git
    - GH_REPO_OCRA_RECIPES_REF: github.com/ocra-recipes/ocra-recipes.git
    - GH_REPO_OCRA_WBI_REF: github.com/ocra-recipes/ocra-wbi-plugins.git

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

before_script:
    - cd $TRAVIS_BUILD_DIR
    - chmod +x generateDocumentationAndDeploy.sh

# Generate and deploy documentation
script:
  - ./generateDocumentationAndDeploy.sh
