var hierarchy =
[
    [ "AdmissibilityConstraintsStruct", "structAdmissibilityConstraintsStruct.html", null ],
    [ "BaseOfSupport", "classBaseOfSupport.html", null ],
    [ "ShapeConstraintsStruct::boundingStruct", "structShapeConstraintsStruct_1_1boundingStruct.html", null ],
    [ "ShapeConstraintsStruct::constancyStruct", "structShapeConstraintsStruct_1_1constancyStruct.html", null ],
    [ "Constraint", "classConstraint.html", [
      [ "AdmissibilityConstraints", "classAdmissibilityConstraints.html", null ],
      [ "Bounding", "classBounding.html", null ],
      [ "Constancy", "classConstancy.html", null ],
      [ "ContactConfigEnforcement", "classContactConfigEnforcement.html", null ],
      [ "ContactConfigHistory", "classContactConfigHistory.html", null ],
      [ "Sequentiality", "classSequentiality.html", null ],
      [ "ShapeConstraints", "classShapeConstraints.html", null ],
      [ "SingleSupport", "classSingleSupport.html", null ],
      [ "SSDSAlternation", "classSSDSAlternation.html", null ]
    ] ],
    [ "AdmissibilityConstraintsStruct::ContactConfigurationEnforcement", "structAdmissibilityConstraintsStruct_1_1ContactConfigurationEnforcement.html", null ],
    [ "AdmissibilityConstraintsStruct::ContactConfigurationHistory", "structAdmissibilityConstraintsStruct_1_1ContactConfigurationHistory.html", null ],
    [ "Thread::ControllerRpcServerCallback", "classThread_1_1ControllerRpcServerCallback.html", null ],
    [ "Thread::DebugRpcServerCallback", "classThread_1_1DebugRpcServerCallback.html", null ],
    [ "ExampleClient", "classExampleClient.html", null ],
    [ "IcubControllerServer", "classIcubControllerServer.html", null ],
    [ "MIQPController", "classMIQPController.html", null ],
    [ "MIQPLinearConstraints", "classMIQPLinearConstraints.html", null ],
    [ "MIQPParameters", "structMIQPParameters.html", null ],
    [ "MIQP::MIQPState", "classMIQP_1_1MIQPState.html", null ],
    [ "MIQPState", "classMIQPState.html", null ],
    [ "ocra_icub::ModelInitializer", "classocra__icub_1_1ModelInitializer.html", null ],
    [ "Module", "classModule.html", null ],
    [ "OcraControllerOptions", "classOcraControllerOptions.html", null ],
    [ "ocra_icub::OcraWbiConversions", "classocra__icub_1_1OcraWbiConversions.html", null ],
    [ "ocra_icub::OcraWbiModel", "classocra__icub_1_1OcraWbiModel.html", null ],
    [ "ocra_icub::OcraWbiModel::OcraWbiModel_pimpl", "structOcraWbiModel_1_1OcraWbiModel__pimpl.html", null ],
    [ "ShapeConstraintsStruct::sequentialityStruct", "structShapeConstraintsStruct_1_1sequentialityStruct.html", null ],
    [ "ShapeConstraintsStruct", "structShapeConstraintsStruct.html", null ],
    [ "singleStepTestParams", "structsingleStepTestParams.html", null ],
    [ "AdmissibilityConstraintsStruct::SingleSupport", "structAdmissibilityConstraintsStruct_1_1SingleSupport.html", null ],
    [ "SittingDemoClient", "classSittingDemoClient.html", null ],
    [ "AdmissibilityConstraintsStruct::SSandDSAlternation", "structAdmissibilityConstraintsStruct_1_1SSandDSAlternation.html", null ],
    [ "StandingDemoClient", "classStandingDemoClient.html", null ],
    [ "StepController", "classStepController.html", null ],
    [ "SteppingDemoClient", "classSteppingDemoClient.html", null ],
    [ "steppingTestParams", "structsteppingTestParams.html", null ],
    [ "TaskOpsClient", "classTaskOpsClient.html", null ],
    [ "Thread", "classThread.html", null ],
    [ "WalkingClient", "classWalkingClient.html", null ],
    [ "WalkingParams", "structWalkingParams.html", null ],
    [ "ZmpController", "classZmpController.html", null ],
    [ "ZmpControllerParams", "structZmpControllerParams.html", null ],
    [ "ZmpPreviewController", "classZmpPreviewController.html", null ],
    [ "ZmpPreviewParams", "structZmpPreviewParams.html", null ]
];